config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: redirect('/session/new')

    resource :session, only: [:new, :create, :destroy]

    resources :users, only: [:show, :new, :create] do
      resources :events, only: [:index, :show]
      resources :closecontacts, only: [:index, :show]
    end
    
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :closecontacts, only: [:new, :create, :edit, :update, :destroy]


  end

app/models/user.rb
class User < ApplicationRecord

  validates :email, :session_token, uniqueness: true

  validates :email,
            :password_digest,
            :session_token,
            presence: true

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :events
  has_many :closecontacts


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    # self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    # BCrypt::Password.new(self.password_digest).is_password?(password)
    self.password_digest == password
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

  def generate_unique_session_token
    token = SecureRandom.urlsafe_base64(16)

    ##
    # Just in case there is a session_token conflict, make sure
    # not to throw a validation error at the user!
    ##
    while self.class.exists?(session_token: token)
      token = SecureRandom.urlsafe_base64(16)
    end

    token
  end

  ##
  # This method is for the mailer!
  ##
  def generate_unique_activation_token
    # e  token = SecureRandom.urlsafe_base64(16)
    token = "activate"
    while self.class.exists?(activation_token: token)
      # e token = SecureRandom.urlsafe_base64(16)
      token = "activate"
    end
    token
  end

  def activate!
    self.update_attribute(:activated, true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # Uncomment these lines to enable the email activation flow
      #-------------------------------------------------------------------------
      #ApplicationMailer.activation_email(@user).deliver_now!
      #flash[:notice] = 'Successfully created your account! Check your inbox for an activation email.'
      #redirect_to new_session_url
      #-------------------------------------------------------------------------

      # And remove these lines
      #---------------------
      #e @user.activate!
      login_user!(@user)
      redirect_to user_events_url(@user.id)
      #---------------------
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  #e def activate
  #   @user = User.find_by(activation_token: params[:activation_token])
  #   @user.activate!
  #   login_user!(@user)
  #   flash[:notice] = 'Successfully activated your account!'
  #   redirect_to root_url
  #e end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="two columns">
            <br>
        </div>
        <div class="eight columns" style="margin-bottom: 0; background-color: darkgray;" >
            <div >
                <form class='form' action="<%= users_url %>" method="post" style="margin-bottom: 0">
                  <input
                    type="hidden"
                    name="authenticity_token"
                    value="<%= form_authenticity_token %>">


                    <label for="new-user-email"></label>
                    <input id='new-user-email' type="text" name="user[email]" class="u-full-width" style="background-color:yellow; text-align: center; margin-bottom: 0;"
                        placeholder="Enter Username">

                    <label for="new-user-password"></label>
                    <input id='new-user-password' type="password" name="user[password]" class="u-full-width" style="background-color:yellow; text-align: center;
                                margin-bottom:0;" placeholder="Enter Password">

                    <input class="u-full-width" type="submit" value="Create account">


                </form>
            </div>

        </div>
        <div class="two columns">
            <br>
        </div>

    </div>
    <div class="row">
        <div class="four columns">
            <br>
        </div>
        <div class="four columns">
            <div style="background-color:rgba(169, 169, 169, 0.671); text-align: center">
                <br>
                <a class='button' href=<%= new_session_url %> >Existing user login</a>



                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>


            </div>
        </div>
        <div class="four columns">
            <br>
        </div>

    </div>
</div>

app/views/users/show.html.erb
<h1 class='page-header'>User Profile</h1>
<p>
  Email: <%= current_user.email %>
</p>