config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: redirect('/session/new')

    resource :session, only: [:new, :create, :destroy]

    resources :users, only: [:show, :new, :create] do
      resources :events, only: [:index, :show]
      resources :closecontacts, only: [:index, :show]
    end
    
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :closecontacts, only: [:new, :create, :edit, :update, :destroy]


  end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :closecontacts_events, dependent: :destroy
  has_many :closecontacts, :through => :closecontacts_events
  validates :date, presence: true
  accepts_nested_attributes_for :closecontacts, reject_if: proc { |attributes| attributes['firstname'].blank? || attributes['secondname'].blank? }

  def nicetitle
      date.strftime("%a %b %d") + " - " + stringy
  end

  def stringy
      s = ""
      closecontacts.each do |cc|
          s.concat(cc.fullname)
          s.concat(", ")
      end
      return s
  end

  def self.to_csv
      attributes = %w{date duration location indoors closecontact_ids}

      CSV.generate(headers: true) do |csv|
          csv << attributes

          all.each do |event|
              array =  attributes.map{ |a| event.send(a) }
              csv << array
          end
      end
  end

  def time
      if date != nil
          date.strftime("%H:%M")
      end
  end

  def assign_ccs(ccs)
      ccs.each {|cc| cc.user = self.user}
      self.closecontacts.append(ccs) if !ccs.nil?
  end

  def newCcForEvent
      raise "problem" if user.nil?
      cc = Closecontact.new
      cc.user = self.user
      self.closecontacts << cc
      return cc
  end
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, :session_token, uniqueness: true

  validates :email,
            :password_digest,
            :session_token,
            presence: true

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :events
  has_many :closecontacts


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    # self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    # BCrypt::Password.new(self.password_digest).is_password?(password)
    self.password_digest == password
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

  def generate_unique_session_token
    token = SecureRandom.urlsafe_base64(16)

    ##
    # Just in case there is a session_token conflict, make sure
    # not to throw a validation error at the user!
    ##
    while self.class.exists?(session_token: token)
      token = SecureRandom.urlsafe_base64(16)
    end

    token
  end

  ##
  # This method is for the mailer!
  ##
  def generate_unique_activation_token
    # e  token = SecureRandom.urlsafe_base64(16)
    token = "activate"
    while self.class.exists?(activation_token: token)
      # e token = SecureRandom.urlsafe_base64(16)
      token = "activate"
    end
    token
  end

  def activate!
    self.update_attribute(:activated, true)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user!

  def index
      @events = current_user.events.sort_by {|e| e.date}

      respond_to do |format|
          format.html
          format.csv { send_data current_user.events.to_csv, filename: "close-contacts.csv" }
      end
    end

  def show
    @event = Event.find(params[:id])
        if @event.user == current_user
            render :show
        else
            redirect_to user_events_url(current_user)
        end
  end

  def new
    @event = Event.new
    @event.user = current_user
    @all_contacts = current_user.closecontacts

    @one = @event.newCcForEvent

    render :new
  end

  def create
      @event = Event.new(event_params)
      @event.closecontacts.each {|c| c.update_attributes(user: current_user)}
      @event.date = get_date_and_time
      @event.user = current_user
      params[:event][:closecontact_ids].each {|id| @event.closecontacts.append(Closecontact.find(id)) if id.length > 0 }

      if @event.save
          redirect_to user_events_url(current_user)
      else
          flash.now[:errors] = @event.errors.full_messages
          render :new
      end
  end

  def edit
      @event = Event.find(params[:id])
      if @event.user == current_user
          @all_contacts = current_user.closecontacts
          render :edit
      else
          redirect_to user_events_url(current_user)
      end
  end

  def update
    @event = Event.find(params[:id])
    ep = event_params
    ep[:date] = get_date_and_time
    @event.assign_attributes(ep)
    @event.closecontacts = []
    @event.assign_ccs(new_ccs)
    @event.assign_ccs(chosen_ccs)

    if (@event.user == current_user) && @event.save
      redirect_to user_events_url(current_user)
    else
      flash.now[:errors] = @event.errors.full_messages
      render :edit
    end
  end

  def chosen_ccs
      chosen_ccs = []
      # params[:event][:closecontact_ids].each {|id| chosen_ccs.append(Closecontact.find(id)) if id.length > 0 }
      @e = Event.new
      @e.closecontact_ids = params[:event][:closecontact_ids]
      # return chosen_ccs.to_set.to_a
      return @e.closecontacts.to_set.to_a
  end

  def new_ccs
      @e = Event.new(event_params)
      return @e.closecontacts
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.user == current_user
        @event.destroy
        redirect_to user_events_url(current_user)
    else
        redirect_to user_events_url(current_user)
    end

  end

  def get_date_and_time
      time = params[:event][:time]
      date = params[:event][:date]
      if (date == nil || time == nil)
          return Time.now
      end
      combine = date + "T" + time
      dt = combine.to_time
      return dt
  end

  private

  def event_params
    params.require(:event).permit(:location, :duration, :closecontact_ids, :indoors, closecontacts_attributes: [ :id, :firstname, :secondname ])
  end
end

app/views/events/_form.html.erb
<div class="container" >
<div class="row">
<div class="four columns">
<br>
</div>
<div class="four columns" style="background-color: darkgray; border-style: solid">

<%= form_for @event do |f| %>
    <%= f.label :date %>
    <%= f.date_field :date, :class => 'u-full-width' %><br />

    <%= f.label :time %>
    <%= f.time_field :time, value: event.time, :class => 'u-full-width' %><br />

    <%= f.label :duration, 'Duration in minutes' %>
    <%= f.number_field :duration, :step => "15", :class => 'u-full-width' %><br />

    <%= f.label :location %>
    <%= f.text_field :location, :class => 'u-full-width' %><br />

    <p>
    <b>Indoors or Outdoors</b>
    <br />
    <%= f.radio_button :indoors, '1' %> Indoors<br />
    <%= f.radio_button :indoors, '0' %> Outdoors<br />
    </p>

    <p>
        <b>Saved Contacts</b>

        <%= f.collection_check_boxes :closecontact_ids, @all_contacts, :id, :fullname do  |b|%>
        <%= b.label(:"data-value" => b.value) { b.check_box + b.text } %>
        <% end %>
    </p>

<p>
    <b>Add a new contact:</b>
    <br>

    <%= f.fields_for :closecontacts, @event.closecontacts.build do |cc_fields| %>

    First name: <%= cc_fields.text_field :firstname %>
    <br>
    Second name: <%= cc_fields.text_field :secondname %>

    <% end %>
</p>










<%= f.submit :class => 'u-full-width' %>
<a class='button u-full-width' href=<%= user_events_url(current_user) %> >Cancel</a>

<% end %>
</div>




<%= render "rack" %>

</div>
</div>

app/views/events/_rack.html.erb
<div class="four columns" style="text-align: left; margin-left: 0;">
    <%= image_tag "File_000.jpeg", :class => "style_image" %>
</div>

app/views/events/edit.html.erb
<!-- <h1 class='page-header'>Edit EventTitle</h1> -->

<%= render "form", event: @event %>

app/views/events/index.html.erb
    <div class="container" style="text-align: center">
        <div class="row">
            <div class="four columns">
                <br>
            </div>
            <div class="four columns" style="background-color: black; text-align: left; border-style: solid">
                <div style="background-color: yellow; text-align: center;">
                    <br>
                    <a class='button u-full-width' href=<%= new_event_url %> >New entry</a>
                    <br>
                    <a class='button u-full-width' href=<%= user_events_url %>.csv >Export All Entries</a>
                    <br>
                    <a class='button u-full-width' href=<%= user_closecontacts_url %> >Contacts</a>

                    <br>

                </div>
                <ul style="list-style-type: none;">
                    <br>

                     <% @events.reverse.each do |event| %>
                        <li><a href="<%= user_event_url(current_user, event) %>"> <%= event.nicetitle %></a></li>
                    <% end %>
                </ul>
                <br>
            </div>
            <%= render "rack" %>




        </div>
    </div>

app/views/events/new.html.erb
<!-- <h1 class='page-header'>New Event Entry</h1> -->

<%= render "form", event: @event %>

app/views/events/show.html.erb
<div class="container" style="text-align: center">
    <div class="row">
        <div class="four columns">
            <br>
        </div>
        <div class="four columns" style="background-color: lightgray;">
            <div style="background-color: yellow; text-align: center;">
                <br>
                <a class='button u-full-width' href="<%= user_events_url(current_user) %>">Home - All entries</a>
                <br>
                <form action="<%= event_url(@event) %>" method="POST" style="margin-bottom: 0rem">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
                    <input type="submit" class="u-full-width" value="Delete Entry" style="margin-bottom: 1rem">
                </form>
                <a class='button u-full-width' href="<%= edit_event_url(@event) %>">Edit Entry</a>
                <br>

            </div>
            <h4>Close-contact Record</h4>
            <table class="u-full-width">
                <tr>
                    <th>Date:</th>
                    <td><%= @event.date.strftime("%d of %B") %></td>
                </tr>
                <tr>
                    <th>Time:</th>
                    <td><%= @event.date.strftime("%H:%M") %></td>
                </tr>
                <tr>
                    <th>Location:</th>
                    <td><%= @event.location %></td>
                </tr>
                <tr>
                    <th>Duration:</th>
                    <td><%= @event.duration %> minutes</td>
                </tr>
                <% event_indoors = @event.indoors ? "indoors" : "outdoors" %>
                <tr>
                    <th>Contact indoors or outdoors:</th>
                    <td><%= event_indoors %></td>
                </tr>

            </table>
            <ul>
                <% @event.closecontacts.each do |cc| %>
                    <li><%= cc.fullname %></li>
                <% end %>
            </ul>
            <br>
        </div>

<%= render "rack" %>
</div>