config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: redirect('/session/new')

    resource :session, only: [:new, :create, :destroy]

    resources :users, only: [:show, :new, :create] do
      resources :events, only: [:index, :show]
      resources :closecontacts, only: [:index, :show]
    end
    
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :closecontacts, only: [:new, :create, :edit, :update, :destroy]


  end

app/models/closecontact.rb
class Closecontact < ApplicationRecord
    validates :firstname, :secondname, presence: true
    belongs_to :user
    has_many :closecontacts_events, dependent: :destroy
    has_many :events, :through => :closecontacts_events

    def fullname
        firstname + " " + secondname
    end


end

app/controllers/closecontacts_controller.rb
class ClosecontactsController < ApplicationController
  before_action :set_closecontact, only: [:show, :edit, :update, :destroy]
  before_action :require_user!
  

  # GET /closecontacts
  # GET /closecontacts.json
  def index
    @closecontacts = current_user.closecontacts
  end

  # GET /closecontacts/1
  # GET /closecontacts/1.json
  def show
      @closecontact = Closecontact.find(params[:id])
          if @closecontact.user == current_user
              render :show
          else
              redirect_to user_closecontacts_url(current_user)
          end
  end

  # GET /closecontacts/new
  def new
    @closecontact = Closecontact.new
  end

  # GET /closecontacts/1/edit
  def edit
      @closecontact = Closecontact.find(params[:id])
      if @closecontact.user == current_user
          render :edit
      else
          redirect_to user_closecontacts_url(current_user)
      end
  end

  # POST /closecontacts
  def create
    @closecontact = Closecontact.new(closecontact_params)
    @closecontact.user = current_user

    if @closecontact.save
        redirect_to user_closecontacts_url(current_user), notice: 'Contact was successfully added.'
    else
        flash.now[:errors] = @closecontact.errors.full_messages
        render :new
    end
  end

  # PATCH/PUT /closecontacts/1
  def update
      @closecontact = Closecontact.find(params[:id])
      if (@closecontact.user == current_user) && @closecontact.update(closecontact_params)
        redirect_to user_closecontacts_url(current_user)
      else
        flash.now[:errors] = @closecontact.errors.full_messages
        render :edit
      end
  end

  # DELETE /closecontacts/1
  # DELETE /closecontacts/1.json
  def destroy
      @closecontact = Closecontact.find(params[:id])
      if @closecontact.user == current_user
          @closecontact.destroy
          redirect_to user_closecontacts_url(current_user)
      else
          redirect_to user_closecontacts_url(current_user)
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_closecontact
      @closecontact = Closecontact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def closecontact_params
      params.require(:closecontact).permit(:firstname, :secondname, :telephone, :email, :regular)
    end

end

app/helpers/closecontacts_helper.rb
module ClosecontactsHelper
end

app/views/closecontacts/_form.html.erb
<%= form_with(model: closecontact, local: true) do |form| %>
  <% if closecontact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(closecontact.errors.count, "error") %> prohibited this closecontact from being saved:</h2>

      <ul>
      <% closecontact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :secondname %>
    <%= form.text_field :secondname %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :regular %>
    <%= form.check_box :regular %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/closecontacts/edit.html.erb
<h1>Editing Closecontact</h1>

<%= render 'form', closecontact: @closecontact %>

<%= link_to 'Show', @closecontact %> |
<%= link_to 'Back', user_closecontacts_url(current_user) %>

app/views/closecontacts/index.html.erb
<div class= "container"

<div class="row">
    <div class="two columns">
        <br>
    </div>

<div class="eight columns" style="background-color: lightgray; border-style: solid">
<br>


<h1>Saved Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Secondname</th>
      <th>Telephone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @closecontacts.each do |closecontact| %>
      <tr>
        <td><%= closecontact.firstname %></td>
        <td><%= closecontact.secondname %></td>
        <td><%= closecontact.telephone %></td>
        <td><%= closecontact.email %></td>
        <td><%= link_to 'Details', user_closecontact_url(current_user, closecontact) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Closecontact', new_closecontact_path %>
<%= link_to 'Homepage', user_events_url(current_user) %>


</div>

    <div class="two columns">
        <br>
    </div>
</div>

app/views/closecontacts/new.html.erb
<h1>New Closecontact</h1>

<%= render 'form', closecontact: @closecontact %>

<%= link_to 'Back', user_closecontacts_url(current_user) %>

app/views/closecontacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @closecontact.firstname %>
</p>

<p>
  <strong>Secondname:</strong>
  <%= @closecontact.secondname %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @closecontact.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @closecontact.email %>
</p>

<p>
  <strong>Regular:</strong>
  <%= @closecontact.regular %>
</p>

<%= link_to 'Edit', edit_closecontact_path(@closecontact) %> |
<%= link_to 'Back', user_closecontacts_url(current_user) %>